### ISSUE TITLE
Better Gulp example

### ISSUE THREAD

**Issue by ai** [lukelarsen/postcss-hidden#2]
You should show in Gulp usages example, that `postcss` function is `gulp-postcss`, not plain `postcss` (a lot of users confused).

**Comment by lukelarsen** [comment]
@ai - Can you explain a bit about what you mean. I think I'm probably one of the confused users. I just found PostCSS recently. Great work on it! I love it.

**Comment by ai** [comment]
This plugin provides 3 other way to make hidden block. But docs has no explanation, why we need this 3 ways and why they are better than `display: none`.

**Comment by lukelarsen** [comment]
I have updated the docs to fix this. I closed the issue that was referencing this.
https://github.com/lukelarsen/postcss-hidden/issues/1

I'm just confused about the Gulp example you mentioned in this issue.

**Comment by ai** [comment]
Ooops, I miss issues :-D 

You need to add `var postcss = require("gulp-postcss")`. Because using just `postcss` in Gulp is very common mistake.

**Comment by lukelarsen** [comment]
Ah now I understand. Thanks. It is more clear if I put that in the example huh.
