### ISSUE TITLE
Send PR to PostCSS README

### ISSUE THREAD

**Issue by ai** [lukelarsen/postcss-hidden#3]
With docs this plugin become awesome. I will promote it tomorrow as a11n tool.

**Comment by lukelarsen** [comment]
What is a 'a11n tool'?

Is there anything needed to close this ticket? The docs have been updated to make them better.

**Comment by ai** [comment]
Just send PR to `postcss/postcss` with your plugin in `Shortcuts` list.

**Comment by simonsmith** [comment]
I made something similar, but I can't remember why on earth I took it off github.

Anyhow, here is the npm package - https://www.npmjs.com/package/postcss-hide

If you want to incorporate any of that then please feel free, I can push my repo back up too

**Comment by lukelarsen** [comment]
Thanks @simonsmith

**Comment by lukelarsen** [comment]
@ai - I submitted PR
https://github.com/postcss/postcss/pull/642
