### ISSUE TITLE
what if i have `content: "disappear"` in my css?

### ISSUE THREAD

**Issue by safareli** [lukelarsen/postcss-hidden#4]
have not checked that case but as i can see you are not checking if decl.prop is `display` and because of that if I have `content: "disappear"` it my css will produce undesired results

**Comment by safareli** [comment]
adding this at the beginning of `walkDecls` callback will fix it
```js
if(decl.prop !== 'display'){
  return
}
```

**Comment by lukelarsen** [comment]
@safareli Thanks! I have fixed this.

**Comment by safareli** [comment]
Welcome :3
