### ISSUE TITLE
Add a changelog.

### ISSUE THREAD

**Issue by ben-eb** [lukelarsen/postcss-hidden#6]
A changelog is required by PostCSS' plugin guidelines. Would you like me to send a PR for a retroactive changelog? Note that this must be kept up to date. :smile:

https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#43-maintain-a-changelog

**Comment by lukelarsen** [comment]
Yeah I'm fine with that. That really just says when changes are made to the plugin the changes are logged somewhere?

Thanks so much. One for the time and two for giving me some examples to learn from.

**Comment by ben-eb** [comment]
> That really just says when changes are made to the plugin the changes are logged somewhere?

Yeah, exactly. :smile:
