### ISSUE TITLE
Accessibility advice for `display: invisible` is incorrect.

### ISSUE THREAD

**Issue by fuzzbomb** [lukelarsen/postcss-hidden#8]
The README states (emphasis mine):

> 3. display: invisible;
>
> Use invisible when you want to hide something while **keeping it available to screen readers and assistive technology** along with letting it take up space in the document. The block will only be visually hidden.
>
>```h3 { display: invisible; }```
>
>Will output
>
>```h3 { visibility: hidden; }```

This is incorrect.  Elements styled with `visibility: hidden` will NOT be conveyed to assistive technology.

Using either `display: none` OR `visibility: hidden` will remove an element from the accessibility tree. As far as assistive technology is concerned, there is no difference between option 1 (display: hidden) and option 3 (display: invisible).

There are 2 options to address this. Either:

- Leave the output behaviour as it is (`visibility: hidden`), but update the documentation. Remove the incorrect statement which says it remains available to assistive technology. Make it clear that this option will hide the element from screen readers.
- Or, leave the documentation as it is, but change the output so it does what the documentation says. If you want content to be visually hidden, take up space, and remain available to screen readers, then `opacity: 0` will achieve that. It works in most screen readers.

**Comment by lukelarsen** [comment]
Thanks for reporting this! I have updated the README.
